[Grouping&Mapping] Improve Search Bar
iTwin/viewer-components-react pull request #306
Opened 2022-08-09 22:24 UTC by arinsasmal

2022-08-10 19:17 UTC, Guillar1 commented
lgtm

2022-08-10 23:08 UTC, Guillar1 approved these changes

2022-08-10 23:27 UTC, Guillar1 requested changes
One more thing, can you make it so the search clears out when you completely delete the all the text?

2022-08-10 23:50 UTC, bingjiez commented on packages/itwin/grouping-mapping-widget/src/widget/components/SelectProject.tsx
> +        <IconButton onClick={() => startSearch() } styleType='borderless'>
Could shorten to onClick={startSearch}

2022-08-11 00:14 UTC, arinsasmal commented on packages/itwin/grouping-mapping-widget/src/widget/components/SelectProject.tsx
> +        <IconButton onClick={() => startSearch() } styleType='borderless'>
Done

2022-08-11 00:21 UTC, Guillar1 approved these changes

2022-08-11 01:01 UTC, merged