Make elements list sorted
iTwin/viewer-components-react pull request #629
Opened 2023-08-23 14:06 UTC by ViliusBa

Sort selected items by their label in an ascending order.

2023-08-23 14:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iTwin/viewer-components-react?pullRequest=629) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/iTwin/viewer-components-react?pullRequest=629) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iTwin/viewer-components-react?pullRequest=629) it.</sub>

2023-08-24 08:10 UTC, saskliutas requested changes

2023-08-24 08:10 UTC, saskliutas commented on packages/itwin/property-grid/src/components/ElementList.tsx
> +async function getSortedLabelToInstanceKeyPairs(labelsProvider: PresentationLabelsProvider, instanceKeys: InstanceKey[]): Promise<RowElementData[]> {
```suggestion
async function getSortedLabelInstanceKeyPairs(labelsProvider: PresentationLabelsProvider, instanceKeys: InstanceKey[]): Promise<RowElementData[]> {
```

2023-08-24 08:10 UTC, saskliutas commented on common/changes/@itwin/property-grid-react/make_elements_list_sorted_2023-08-23-13-59.json
> +      "comment": "Sort selected items by their label in an ascending order.  ",
```suggestion
      "comment": "Sort selected elements list by label in an ascending order. ",
```

2023-08-24 08:46 UTC, saskliutas approved these changes

2023-08-24 08:46 UTC, saskliutas commented on common/changes/@itwin/property-grid-react/make_elements_list_sorted_2023-08-23-13-59.json
> +      "comment": "Sort selected elements list by label in an ascending order. ",
I missed one more space. 😞 

```suggestion
      "comment": "Sort selected elements list by label in an ascending order.",
```

2023-08-25 06:59 UTC, ViliusBa commented on packages/itwin/property-grid/src/components/ElementList.tsx
> +  });
Didn't know that such a method exists, thanks. Will adjust

2023-08-25 07:32 UTC, ViliusBa commented on packages/itwin/property-grid/src/components/ElementList.tsx
> +  });
Didn't know that such a method exists, thanks. Will adjust

2023-08-25 08:06 UTC, merged