Add lint error checking for scss files
iTwin/viewer-components-react pull request #691
Opened 2023-11-10 13:45 UTC by ViliusBa

Closes #687 

With this PR *.scss files will be checked for lint to warn if standard scss guidelines are broken in `tree-widget` or `property-grid`.

2023-11-10 14:40 UTC, aruniverse approved these changes
Missing rush change

2023-11-13 11:09 UTC, saskliutas requested changes

2023-11-13 11:09 UTC, saskliutas commented on packages/itwin/tree-widget/package.json
> +    "lint": "eslint -f visualstudio \"./src/**/*.{ts,tsx}\" 1>&2 && npx stylelint \"**/*.scss\"",
`npx` shouldn't be needed.

```suggestion
    "lint": "eslint -f visualstudio \"./src/**/*.{ts,tsx}\" 1>&2 && stylelint \"./src/**/*.scss\"",
```

Maybe separate scripts for `eslint` and `stylelint`?
```
"lint": "npm run lint:eslint && npm run lint:stylelint",
"lint:eslint": "eslint -f visualstudio \"./src/**/*.{ts,tsx}\" 1>&2",
"lint:stylelint": "stylelint \"./src/**/*.scss\"",
```

2023-11-13 11:09 UTC, saskliutas commented on packages/itwin/property-grid/package.json
> +    "lint": "eslint -f visualstudio \"./src/**/*.{ts,tsx}\" 1>&2 && npx stylelint \"**/*.scss\"",
`npx` shouldn't be needed.
```suggestion
    "lint": "eslint -f visualstudio \"./src/**/*.{ts,tsx}\" 1>&2 && stylelint \"./src/**/*.scss\"",
```

Maybe separate scripts for `eslint` and `stylelint`?
```
"lint": "npm run lint:eslint && npm run lint:stylelint",
"lint:eslint": "eslint -f visualstudio \"./src/**/*.{ts,tsx}\" 1>&2",
"lint:stylelint": "stylelint \"./src/**/*.scss\"",
```

2023-11-13 12:14 UTC, saskliutas requested changes

2023-11-13 12:14 UTC, saskliutas commented on packages/itwin/tree-widget/src/components/trees/VisibilityTreeBase.scss
> +      &.enlarge {
Looks like this is a duplicate of the one on line 8

2023-11-15 09:36 UTC, saskliutas approved these changes

2023-11-15 09:54 UTC, merged