Fix flaky e2e tests in PropertyGrid
iTwin/viewer-components-react pull request #717
Opened 2023-12-18 17:26 UTC by ViliusBa

Closes #713 

Ran these tests 100 times each, all passed. It seems that ensuring that properties are loaded for the first selected item helped.

2023-12-18 18:20 UTC, ben-polinsky approved these changes

2023-12-19 05:40 UTC, grigasp commented
> It seems that ensuring that properties are loaded for the first selected item helped.

Could you reproduce this without the change? I don't agree that waiting for the load to complete before clicking on the second node is the solution - users may not know they need to wait :)

2023-12-20 14:30 UTC, grigasp commented on common/changes/@itwin/property-grid-react/property-grid-fix-flaky-tests_2023-12-18-17-19.json
> +      "comment": "",
Looks like a legit patch - need a change message.

2023-12-20 14:30 UTC, grigasp commented on packages/itwin/property-grid/src/e2e-tests/PropertyGrid.test.ts
> +* See LICENSE.md in the project root for license terms and full copyright notice.
should changes in this file be reverted?

2023-12-20 15:05 UTC, saskliutas requested changes

2023-12-20 15:05 UTC, saskliutas commented on packages/itwin/property-grid/src/hooks/UseInstanceInfo.ts
> +  }, [dataProvider, dataProvider.onDataChanged]);
```suggestion
  }, [dataProvider]);
```

2023-12-21 12:41 UTC, saskliutas approved these changes

2023-12-21 12:41 UTC, merged