Bump AppUI version and unskip related e2e tests
iTwin/viewer-components-react pull request #720
Opened 2023-12-21 15:55 UTC by ViliusBa

Closes #710

2023-12-21 15:56 UTC, aruniverse approved these changes

2023-12-22 08:03 UTC, saskliutas requested changes

2023-12-22 08:03 UTC, saskliutas commented on packages/itwin/property-grid/package.json
> +    "@itwin/components-react": "^4.8.0",
You need to bump appui version in test-viewer to see appui fix in e2e tests

2024-01-11 07:42 UTC, grigasp commented
Tree widget tests fail due to an issue in appui - waiting for [the fix](https://github.com/iTwin/appui/pull/668) to be released.

2024-01-12 12:02 UTC, saskliutas approved these changes

2024-01-12 12:02 UTC, merged